import React from "react";
export var GenericDetailTimeline = function () {
    return (React.createElement("div", { className: "card mb-4" },
        React.createElement("h5", { className: "card-header" }, "User Activity Timeline"),
        React.createElement("div", { className: "card-body" },
            React.createElement("ul", { className: "timeline" },
                React.createElement("li", { className: "timeline-item timeline-item-transparent" },
                    React.createElement("span", { className: "timeline-point timeline-point-primary" }),
                    React.createElement("div", { className: "timeline-event" },
                        React.createElement("div", { className: "timeline-header mb-1" },
                            React.createElement("h6", { className: "mb-0" }, "12 Invoices have been paid"),
                            React.createElement("small", { className: "text-muted" }, "12 min ago")),
                        React.createElement("p", { className: "mb-2" }, "Invoices have been paid to the company"),
                        React.createElement("div", { className: "d-flex" },
                            React.createElement("a", { href: "javascript:void(0)", className: "me-3" },
                                React.createElement("img", { src: "../../assets/img/icons/misc/pdf.png", alt: "PDF image", width: "15", className: "me-2" }),
                                React.createElement("span", { className: "fw-bold text-body" }, "invoices.pdf"))))),
                React.createElement("li", { className: "timeline-item timeline-item-transparent" },
                    React.createElement("span", { className: "timeline-point timeline-point-warning" }),
                    React.createElement("div", { className: "timeline-event" },
                        React.createElement("div", { className: "timeline-header mb-1" },
                            React.createElement("h6", { className: "mb-0" }, "Client Meeting"),
                            React.createElement("small", { className: "text-muted" }, "45 min ago")),
                        React.createElement("p", { className: "mb-2" }, "Project meeting with john @10:15am"),
                        React.createElement("div", { className: "d-flex flex-wrap" },
                            React.createElement("div", { className: "avatar me-3" },
                                React.createElement("img", { src: "../../assets/img/avatars/3.png", alt: "Avatar", className: "rounded-circle" })),
                            React.createElement("div", null,
                                React.createElement("h6", { className: "mb-0" }, "Lester McCarthy (Client)"),
                                React.createElement("span", { className: "text-muted" }, "CEO of ThemeSelection"))))),
                React.createElement("li", { className: "timeline-item timeline-item-transparent" },
                    React.createElement("span", { className: "timeline-point timeline-point-info" }),
                    React.createElement("div", { className: "timeline-event" },
                        React.createElement("div", { className: "timeline-header mb-1" },
                            React.createElement("h6", { className: "mb-0" }, "Create a new project for client"),
                            React.createElement("small", { className: "text-muted" }, "2 Day Ago")),
                        React.createElement("p", { className: "mb-2" }, "5 team members in a project"),
                        React.createElement("div", { className: "d-flex align-items-center avatar-group" },
                            React.createElement("div", { className: "avatar pull-up", "data-bs-toggle": "tooltip", "data-popup": "tooltip-custom", "data-bs-placement": "top", title: "", "data-bs-original-title": "Vinnie Mostowy" },
                                React.createElement("img", { src: "../../assets/img/avatars/5.png", alt: "Avatar", className: "rounded-circle" })),
                            React.createElement("div", { className: "avatar pull-up", "data-bs-toggle": "tooltip", "data-popup": "tooltip-custom", "data-bs-placement": "top", title: "", "data-bs-original-title": "Marrie Patty" },
                                React.createElement("img", { src: "../../assets/img/avatars/12.png", alt: "Avatar", className: "rounded-circle" })),
                            React.createElement("div", { className: "avatar pull-up", "data-bs-toggle": "tooltip", "data-popup": "tooltip-custom", "data-bs-placement": "top", title: "", "data-bs-original-title": "Jimmy Jackson" },
                                React.createElement("img", { src: "../../assets/img/avatars/9.png", alt: "Avatar", className: "rounded-circle" })),
                            React.createElement("div", { className: "avatar pull-up", "data-bs-toggle": "tooltip", "data-popup": "tooltip-custom", "data-bs-placement": "top", title: "", "data-bs-original-title": "Kristine Gill" },
                                React.createElement("img", { src: "../../assets/img/avatars/6.png", alt: "Avatar", className: "rounded-circle" })),
                            React.createElement("div", { className: "avatar pull-up", "data-bs-toggle": "tooltip", "data-popup": "tooltip-custom", "data-bs-placement": "top", title: "", "data-bs-original-title": "Nelson Wilson" },
                                React.createElement("img", { src: "../../assets/img/avatars/14.png", alt: "Avatar", className: "rounded-circle" }))))),
                React.createElement("li", { className: "timeline-item timeline-item-transparent" },
                    React.createElement("span", { className: "timeline-point timeline-point-success" }),
                    React.createElement("div", { className: "timeline-event" },
                        React.createElement("div", { className: "timeline-header mb-1" },
                            React.createElement("h6", { className: "mb-0" }, "Design Review"),
                            React.createElement("small", { className: "text-muted" }, "5 days Ago")),
                        React.createElement("p", { className: "mb-0" }, "Weekly review of freshly prepared design for our new app."))),
                React.createElement("li", { className: "timeline-end-indicator" },
                    React.createElement("i", { className: "bx bx-check-circle" }))))));
};
