"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WidgetTimeline = exports.WidgetDouble = exports.WidgetTable = exports.WidgetList = exports.WidgetInfo = void 0;
var widget_info_component_1 = require("./widget-info.component");
Object.defineProperty(exports, "WidgetInfo", { enumerable: true, get: function () { return widget_info_component_1.WidgetInfo; } });
var widget_list_component_1 = require("./widget-list.component");
Object.defineProperty(exports, "WidgetList", { enumerable: true, get: function () { return widget_list_component_1.WidgetList; } });
var widget_table_component_1 = require("./widget-table.component");
Object.defineProperty(exports, "WidgetTable", { enumerable: true, get: function () { return widget_table_component_1.WidgetTable; } });
var widget_double_component_1 = require("./widget-double.component");
Object.defineProperty(exports, "WidgetDouble", { enumerable: true, get: function () { return widget_double_component_1.WidgetDouble; } });
var widget_timeline_component_1 = require("./widget-timeline.component");
Object.defineProperty(exports, "WidgetTimeline", { enumerable: true, get: function () { return widget_timeline_component_1.WidgetTimeline; } });
